### ISSUE TITLE
Book Question

### ISSUE THREAD

**Issue by TheTwitchy** [knaffles/LearnPHP#1]
Hi! Quick question, what book (or website) is this repo from?

**Comment by knaffles** [comment]
Hi there.

All the exercises (everything except the "meals" directory) are from Murach's MySQL and PHP:

https://www.murach.com/shop/murach-s-php-and-mysql-2nd-edition-detail

But the stuff here is from a really old edition. Not sure how you came across it, but I would probably suggest looking for more updated code.

**Comment by TheTwitchy** [comment]
Ah, thank you! I spent a lot of time trying to figure out where this was from, originally found it on Google, the reason is base64 encoded below. 

VGhlcmUncyBhIHZ1bG5lcmFiaWxpdHkgaW4gdGhpcyBjb2RlIHRoYXQgYWxsb3dzIGZvciBzZXJ2ZXIgdGFrZW92ZXIsIEknbSBub3RpZnlpbmcgcGVvcGxlIHdobyd2ZSBleHBvc2VkIHRoaXMgY29kZSBvbiBwdWJsaWMgc2l0ZXMsIGFzIHdlbGwgYXMgdGhlIG9yaWdpbmFsIGF1dGhvciwgaWYgdGhleSdyZSBzdGlsbCBhcm91bmQuIEkndmUgb2JmdXNjYXRlZCB0aGlzIHNwZWNpZmljYWxseSBiZWNhdXNlIEkgZG9uJ3Qgd2FudCB0aGlzIHRvIHNob3cgdXAgaW4gc2VhcmNoIGVuZ2luZXMu
